
name: 'bolt_dbt_snapchat_package'
version: '1.0.0'
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: 'bolt_dbt_snapchat_package'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]


target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"

vars:
    # General vars
    week_start: 'Monday' # Abbreviation and full name both work
    currency: "USD"

models:
  bolt_dbt_snapchat_package:
    base:
      +schema: snapchat_base
      +materialized: table
    reporting:
        +schema: reporting
        +materialized: table
